In [1]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
from IPython.display import Image

In [5]:
import numpy as np
print(np.__version__)

1.19.2


### 1. numpy의 reshape() 메소드 사용

In [19]:
arr = np.arange(0, 32)
print(len(arr))
print(arr)
print(type(arr))
print(arr.shape)

32
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
<class 'numpy.ndarray'>
(32,)


In [20]:
arr_reshape = arr.reshape(4, 2, 4)
print(arr_reshape)
print(arr_reshape.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]]]
(4, 2, 4)


### 2. numpy의 sum() 메소드 사용

In [26]:
print(arr_reshape.ndim)

3


In [28]:
# axis = None
print(arr_reshape.shape)
print(arr_reshape.sum())
print(arr_reshape.ndim)

(4, 2, 4)
496
3


In [31]:
# axis = 0
arr_reahspe_sum = arr_reshape.sum(axis = 0)
print(arr_reahspe_sum.shape)
print(arr_reahspe_sum)
print(arr_reahspe_sum.ndim)

(2, 4)
[[48 52 56 60]
 [64 68 72 76]]
2


In [32]:
# axis = 1
arr_reahspe_sum = arr_reshape.sum(axis = 1)
print(arr_reahspe_sum.shape)
print(arr_reahspe_sum)
print(arr_reahspe_sum.ndim)

(4, 4)
[[ 4  6  8 10]
 [20 22 24 26]
 [36 38 40 42]
 [52 54 56 58]]
2


In [33]:
# axis = 2
arr_reahspe_sum = arr_reshape.sum(axis = 2)
print(arr_reahspe_sum.shape)
print(arr_reahspe_sum)
print(arr_reahspe_sum.ndim)

(4, 2)
[[  6  22]
 [ 38  54]
 [ 70  86]
 [102 118]]
2


### 3. numpy의 array() 메소드 사용

In [6]:
def arr_print(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr)

In [12]:
# 1차원 list로 numpy 배열 만들기
arr = [1, 2, 3]
print(type(arr))
arr_arr = np.array(arr)
arr_print(arr_arr)

<class 'list'>
type: <class 'numpy.ndarray'>
shape: (3,), dimension : 1, dtype : int32
numpy 배열의 데이터
 [1 2 3]


In [13]:
# 2차원 list로 numpy 배열 만들기
arr = [[1, 2, 3], [4, 5, 6]]
print(type(arr))
# arr_np = np.array(arr) # dtype이 암시적으로 int32로 만들어짐
# arr_np = np.array(arr, dtype = float) # dtype이 명시적으로 float로 바뀜
arr_arr = np.array(arr, dtype = np.float32) # dtype 뒤에 숫자를 적을 시 np를 앞에 작성해야 함
arr_print(arr_arr)

<class 'list'>
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : float32
numpy 배열의 데이터
 [[1. 2. 3.]
 [4. 5. 6.]]


In [37]:
# 3차원 list로 numpy 배열 만들기
arr = [[[1, 2, 3], [4, 5, 6]] , [[11, 12, 13], [14, 15, 16]]]
print(type(arr))
arr_arr = np.array(arr, dtype = int)
arr_print(arr_arr)

<class 'list'>
type: <class 'numpy.ndarray'>
shape: (2, 2, 3), dimension : 3, dtype : int32
numpy 배열의 데이터
 [[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


### 4. numpy의 zero() 메소드 사용

In [39]:
a = np.zeros(shape=(3,4))
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [41]:
a = np.zeros(shape=(3,4), dtype = np.int16)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension : 2, dtype : int16
numpy 배열의 데이터
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


### 5. numpy의 ones() 메소드 사용

In [45]:
a = np.ones(shape=(2,3,4), dtype = int)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (2, 3, 4), dimension : 3, dtype : int32
numpy 배열의 데이터
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


### 6. numpy의 full() 메소드 사용

In [49]:
a = np.full(shape=(2,3), fill_value = 7)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[7 7 7]
 [7 7 7]]


### 7. numpy의 eye() 메소드 사용

In [50]:
a = np.eye(5)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (5, 5), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 8. numpy의 empty() 메소드 사용

In [51]:
a = np.empty(shape=(4,2))
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (4, 2), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[1.27319747e-313 2.12199579e-313]
 [4.66839074e-313 5.51718906e-313]
 [8.06358401e-313 8.91238232e-313]
 [1.14587773e-312 1.23075756e-312]]


### 9. numpy의 like() 메소드 사용

In [52]:
a = np.array([[1,2,3],[4,5,6]])
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[1 2 3]
 [4 5 6]]


In [53]:
a_zeros = np.zeros_like(a)
arr_print(a_zeros)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[0 0 0]
 [0 0 0]]


In [54]:
a_ones = np.ones_like(a)
arr_print(a_ones)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[1 1 1]
 [1 1 1]]


In [56]:
a_full = np.full_like(a, 999)
arr_print(a_full)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[999 999 999]
 [999 999 999]]


In [57]:
a_empty = np.empty_like(a)
arr_print(a_empty)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[180270816       336         0]
 [        0         1 677733225]]
