In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

import numpy as np
import matplotlib.pyplot as plt

In [2]:
def arr_print(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr)

### 1. numpy의 save(), savez() 메소드  사용

In [9]:
a = np.random.randint(0, 10, (2,3))
arr_print(a)
b = np.random.randint(0, 10, (2,3))
arr_print(b)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[5 3 4]
 [7 8 1]]
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[0 1 7]
 [6 6 8]]


In [5]:
np.save('.\output\my_arr1', a)
np.savez('.\output\my_arr2', a, b)

In [8]:
print(np.load('.\output\my_arr1.npy'))

print(np.load('.\output\my_arr2.npz')) # <numpy.lib.npyio.NpzFile object at 0x000001D67EF6D340>
npzfiles = np.load('.\output\my_arr2.npz')
print(npzfiles['arr_0'])
print(npzfiles['arr_1'])

[[6 0 4]
 [2 4 5]]
[[6 0 4]
 [2 4 5]]
[[9 1 8]
 [4 9 2]]


### 2. numpy의 savetxt() 메소드 사용

In [10]:
data = np.random.random((3,4))
arr_print(data)

type: <class 'numpy.ndarray'>
shape: (3, 4), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.39741915 0.56133952 0.33320376 0.48223088]
 [0.30061181 0.40566189 0.6787462  0.59570582]
 [0.70687067 0.07743368 0.35567876 0.40876927]]


In [13]:
np.savetxt('./output/saved.csv', data, delimiter=',')
np.savetxt('./output/saved.tsv', data, delimiter='\t')

In [20]:
print(np.loadtxt('./output/saved.csv', dtype=float, delimiter=','))

[[0.39741915 0.56133952 0.33320376 0.48223088]
 [0.30061181 0.40566189 0.6787462  0.59570582]
 [0.70687067 0.07743368 0.35567876 0.40876927]]
