In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

import numpy as np
import matplotlib.pyplot as plt

In [2]:
def arr_print(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr)

In [3]:
a = np.arange(1, 10).reshape(3,3)
arr_print(a)
b = np.arange(9, 0, -1).reshape(3,3)
arr_print(b)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


### 1. 산술연산자

In [6]:
arr_print(a + b)
arr_print(np.add(a, b))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [7]:
arr_print(a - b)
arr_print(np.subtract(a, b))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [10]:
arr_print(a * b)
arr_print(np.multiply(a, b))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [11]:
arr_print(a / b)
arr_print(np.divide(a, b))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.11111111 0.25       0.42857143]
 [0.66666667 1.         1.5       ]
 [2.33333333 4.         9.        ]]


### 2. 비교 연산

In [23]:
print(a == b)

[[False False False]
 [False  True False]
 [False False False]]


In [24]:
print(np.array_equal(a,b))

False


### 3. 함수

In [20]:
arr_print(np.exp(a))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [19]:
arr_print(np.log(a))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


### 4. 삼각함수

In [21]:
arr_print(np.sin(a))
arr_print(np.cos(a))
arr_print(np.tan(a))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]
 [ 0.87144798 -6.79971146 -0.45231566]]


### 5. 그 외

In [22]:
arr_print(np.sqrt(a))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [18]:
arr_print(np.dot(a,b))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
