In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

import numpy as np
import matplotlib.pyplot as plt

In [2]:
def arr_print(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr)

### 1. shape이 같은 두 배열의 연산

In [5]:
a = np.arange(1, 25).reshape(4,6)
arr_print(a)
b = np.arange(25, 49).reshape(4,6)
arr_print(b)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [6]:
arr_print(a+b)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[26 28 30 32 34 36]
 [38 40 42 44 46 48]
 [50 52 54 56 58 60]
 [62 64 66 68 70 72]]


### 2. shape이 다른 두 배열의 연산

In [8]:
arr_print(a+100)

new_arr = np.full_like(a, 100)
arr_print(new_arr)
arr_print(a+new_arr)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]
 [100 100 100 100 100 100]]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [11]:
c = np.arange(5).reshape(1,5)
arr_print(c)
d = np.arange(5).reshape(5,1)
arr_print(d)

arr_print(c+d)

type: <class 'numpy.ndarray'>
shape: (1, 5), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[0 1 2 3 4]]
type: <class 'numpy.ndarray'>
shape: (5, 1), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[0]
 [1]
 [2]
 [3]
 [4]]
type: <class 'numpy.ndarray'>
shape: (5, 5), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
