In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

import numpy as np
import matplotlib.pyplot as plt

In [3]:
def arr_print(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr)

In [4]:
a = np.random.randint(0, 9, (3,3))
arr_print(a)

a[:, 0] = 999 # a 배열의 모든 행의 0번째 열을 999로 변경함
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[8 7 4]
 [3 3 0]
 [6 0 3]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[999   7   4]
 [999   3   0]
 [999   0   3]]


In [5]:
copied_a = np.copy(a)
arr_print(copied_a)
copied_a[:, 1] = 777
arr_print(copied_a)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[999   7   4]
 [999   3   0]
 [999   0   3]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[999 777   4]
 [999 777   0]
 [999 777   3]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[999   7   4]
 [999   3   0]
 [999   0   3]]
