In [2]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

import numpy as np
import matplotlib.pyplot as plt

In [3]:
def arr_print(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr)

In [13]:
unsorted_arr = np.random.random((3,3))
arr_print(unsorted_arr)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.15385632 0.01183112 0.51515856]
 [0.81651242 0.69952573 0.94975273]
 [0.63214397 0.26688611 0.09803005]]


In [9]:
unsorted_arr1 = unsorted_arr.copy()
unsorted_arr2 = unsorted_arr.copy()
unsorted_arr3 = unsorted_arr.copy()

In [14]:
unsorted_arr1.sort()
arr_print(unsorted_arr1)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.08042216 0.43157323 0.55062808]
 [0.10996733 0.22640553 0.44447398]
 [0.08086576 0.35740032 0.93091584]]


In [15]:
unsorted_arr2.sort(axis = 0)
arr_print(unsorted_arr2)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.08086576 0.35740032 0.08042216]
 [0.10996733 0.43157323 0.22640553]
 [0.55062808 0.44447398 0.93091584]]


In [16]:
unsorted_arr3.sort(axis = 1)
arr_print(unsorted_arr2)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : float64
numpy 배열의 데이터
 [[0.08086576 0.35740032 0.08042216]
 [0.10996733 0.43157323 0.22640553]
 [0.55062808 0.44447398 0.93091584]]
