In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

import numpy as np
import matplotlib.pyplot as plt

In [2]:
def arr_print(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr)

In [3]:
a0 = np.arange(24)
arr_print(a0)
a1 = np.arange(24).reshape(4,6)
arr_print(a1)
a2 = np.arange(24).reshape(2,4,3)
arr_print(a2)

type: <class 'numpy.ndarray'>
shape: (24,), dimension : 1, dtype : int32
numpy 배열의 데이터
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
type: <class 'numpy.ndarray'>
shape: (2, 4, 3), dimension : 3, dtype : int32
numpy 배열의 데이터
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


### 1. 1차원 배열 요소 참조 및 변경

In [4]:
print(a0[5])

a0[0] = 1000000
print(a0)

5
[1000000       1       2       3       4       5       6       7       8
       9      10      11      12      13      14      15      16      17
      18      19      20      21      22      23]


### 2. 2차원 배열 요소 참조 및 변경

In [5]:
print(a1[0][1])
print(a1[0,1])

a1[0][1] = 100000
a1[1,3] = 30000
print(a1)

1
1
[[     0 100000      2      3      4      5]
 [     6      7      8  30000     10     11]
 [    12     13     14     15     16     17]
 [    18     19     20     21     22     23]]


### 3. 3차원 배열 요소 참조 및 변경

In [6]:
print(a2[1][0][1])
print(a2[1,2,1])

a2[1][0][1] = 444
a2[1,3,2] = 333
print(a2)

13
19
[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]]

 [[ 12 444  14]
  [ 15  16  17]
  [ 18  19  20]
  [ 21  22 333]]]


### 4. 불린 인덱싱

In [7]:
a = np.arange(24).reshape(4,6)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [9]:
# a 배열에서 요소의 값이 짝수인 요수의 총 합계
# numpy의 브로드캐스팅을 이용해서 짝수인 배열의 요소를 확인함
even_arr = a % 2 == 0
arr_print(even_arr);

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : bool
numpy 배열의 데이터
 [[ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]
 [ True False  True False  True False]]


In [10]:
# 불린 인덱싱을 이용하면 결과가 True인 요소들만 조회함
print(a[a%2==0])

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [12]:
print(np.sum(a[a%2==0]))
print(np.sum(a[a%2==1]))

132
144


불린 인덱싱 응용

2014년 시애틀 1월 평균 강수량

In [13]:
import pandas as pd

In [15]:
rain_in_seattle = pd.read_csv('./data/Seattle2014.csv')
rain_in_seattle

STATION                                STATION_NAME      DATE  \
0    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140101   
1    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140102   
2    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140103   
3    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140104   
4    GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20140105   
..                 ...                                         ...       ...   
360  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141227   
361  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141228   
362  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141229   
363  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141230   
364  GHCND:USW00024233  SEATTLE TACOMA INTERNATIONAL AIRPORT WA US  20141231   

     PRCP  SNWD  SNOW  TMAX  TMIN  AWND  WDF2  WDF5  WSF2  WSF5  WT01  WT05  \
0       0     0     0    72    33    12   340   310    36    40 -9999 -9999   
1      41     0     0   106    61    32   190   200    94   116 -9999 -9999   
2      15     0     0    89    28    26    30    50    63    72     1 -9999   
3       0     0     0    78     6    27    40    40    45    58     1 -9999   
4       0     0     0    83    -5    37    10    10    67    76 -9999 -9999   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
360    33     0     0    94    44    49   210   210   112   161     1 -9999   
361    41     0     0    67    28    18    50    30    58    72     1 -9999   
362     0     0     0    61     6    43   350   350    76   103     1 -9999   
363     0     0     0    33   -21    36    90    70    63    76 -9999 -9999   
364     0     0     0    33   -27    30    30 -9999    58 -9999 -9999 -9999   

     WT02  WT03  
0   -9999 -9999  
1   -9999 -9999  
2   -9999 -9999  
3   -9999 -9999  
4   -9999 -9999  
..    ...   ...  
360 -9999 -9999  
361 -9999 -9999  
362 -9999 -9999  
363 -9999 -9999  
364 -9999 -9999  

[365 rows x 17 columns]

In [18]:
rain_arr = rain_in_seattle['PRCP'].values
rain_arr

array([  0,  41,  15,   0,   0,   3, 122,  97,  58,  43, 213,  15,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   5,   0,   0,   0,   0,
         0,  89, 216,   0,  23,  20,   0,   0,   0,   0,   0,   0,  51,
         5, 183, 170,  46,  18,  94, 117, 264, 145, 152,  10,  30,  28,
        25,  61, 130,   3,   0,   0,   0,   5, 191, 107, 165, 467,  30,
         0, 323,  43, 188,   0,   0,   5,  69,  81, 277,   3,   0,   5,
         0,   0,   0,   0,   0,  41,  36,   3, 221, 140,   0,   0,   0,
         0,  25,   0,  46,   0,   0,  46,   0,   0,   0,   0,   0,   0,
         5, 109, 185,   0, 137,   0,  51, 142,  89, 124,   0,  33,  69,
         0,   0,   0,   0,   0, 333, 160,  51,   0,   0, 137,  20,   5,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  38,
         0,  56,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,  18,  64,   0,   5,  36,  13,   0,
         8,   3,   0,   0,   0,   0,   0,   0,  18,  23,   0,   

In [19]:
print('Data Size : ', len(rain_arr))

Data Size :  365


In [23]:
# 날짜 배열
day_arr = np.arange(0, 365)
print(day_arr)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [26]:
# 1월을 날 수 만큼 불린 인덱싱 생성
condition_jan = day_arr < 31 
print(condition_jan[:40])

[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True False False False False False
 False False False False]


In [27]:
# 1월의 강수량만 추출
rain_jan = rain_arr[condition_jan]
print(rain_jan)
print(len(rain_jan))

[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]
31


In [29]:
print('1월 강수량 합계 : {}'.format(np.sum(rain_jan)))
print('1월 강수량 평균 : {}'.format(np.mean(rain_jan)))

1월 강수량 합계 : 940
1월 강수량 평균 : 30.322580645161292


### 5. 팬시 인덱싱

In [30]:
arr = np.arange(1, 25).reshape(4,6)
arr_print(arr)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [38]:
print(arr[0,0], arr[1,1], arr[2,2], arr[3,3])
arr_1 = arr[0,0], arr[1,1], arr[2,2], arr[3,3]
print(arr_1)
print(type(arr_1))

print(arr[[0,1,2,3,],[0,1,2,3,]])
arr_1 = [arr[0,0], arr[1,1], arr[2,2], arr[3,3]]
print(arr_1)
print(type(arr_1))

1 8 15 22
(1, 8, 15, 22)
<class 'tuple'>
[ 1  8 15 22]
[1, 8, 15, 22]
<class 'list'>


In [39]:
print(arr[:, [1,2]])
print(type(arr[:, [1,2]]))

[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]]
<class 'numpy.ndarray'>
