In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

import numpy as np
import matplotlib.pyplot as plt

In [2]:
def arr_print(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr)

In [5]:
a0 = np.arange(24)
arr_print(a0)

arr_print(a0[2:6])

type: <class 'numpy.ndarray'>
shape: (24,), dimension : 1, dtype : int32
numpy 배열의 데이터
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
type: <class 'numpy.ndarray'>
shape: (4,), dimension : 1, dtype : int32
numpy 배열의 데이터
 [2 3 4 5]


In [19]:
a1 = np.arange(24).reshape(4,6)
arr_print(a1)

arr_print(a1[1:3])
arr_print(a1[:, 1:5])
arr_print(a1[1:3, 1:5])
arr_print(a1[1:-1, 1:-1])

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
type: <class 'numpy.ndarray'>
shape: (2, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
type: <class 'numpy.ndarray'>
shape: (4, 4), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 1  2  3  4]
 [ 7  8  9 10]
 [13 14 15 16]
 [19 20 21 22]]
type: <class 'numpy.ndarray'>
shape: (2, 4), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 7  8  9 10]
 [13 14 15 16]]
type: <class 'numpy.ndarray'>
shape: (2, 4), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 7  8  9 10]
 [13 14 15 16]]


In [20]:
slicing_arr = a1[1:3, 1:5]
arr_print(slicing_arr)
arr_print(slicing_arr[:, 1:3])
slicing_arr[:, 1:3] = 999
arr_print(slicing_arr)

arr_print(a1)

type: <class 'numpy.ndarray'>
shape: (2, 4), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 7  8  9 10]
 [13 14 15 16]]
type: <class 'numpy.ndarray'>
shape: (2, 2), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 8  9]
 [14 15]]
type: <class 'numpy.ndarray'>
shape: (2, 4), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[  7 999 999  10]
 [ 13 999 999  16]]
type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[  0   1   2   3   4   5]
 [  6   7 999 999  10  11]
 [ 12  13 999 999  16  17]
 [ 18  19  20  21  22  23]]


In [9]:
a2 = np.arange(24).reshape(2,4,3)
print(a2)

arr_print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
