## 배열 변환

In [1]:
import warnings
warnings.filterwarnings('ignore')
from IPython.display import Image

import numpy as np
import matplotlib.pyplot as plt

In [2]:
def arr_print(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr)

### 1. 전치

In [3]:
a = np.random.randint(1,10,(2,3))
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[3 5 9]
 [2 2 7]]


In [4]:
arr_print(a.T)

type: <class 'numpy.ndarray'>
shape: (3, 2), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[3 2]
 [5 2]
 [9 7]]


### 2. 배열 형태 변경

ravel()

In [5]:
a = np.random.randint(1,10,(2,3))
arr_print(a)
arr_print(a.ravel())

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[7 4 6]
 [2 4 5]]
type: <class 'numpy.ndarray'>
shape: (6,), dimension : 1, dtype : int32
numpy 배열의 데이터
 [7 4 6 2 4 5]


In [6]:
b = a.ravel()
arr_print(b)
b[0] = 999
arr_print(b)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (6,), dimension : 1, dtype : int32
numpy 배열의 데이터
 [7 4 6 2 4 5]
type: <class 'numpy.ndarray'>
shape: (6,), dimension : 1, dtype : int32
numpy 배열의 데이터
 [999   4   6   2   4   5]
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[999   4   6]
 [  2   4   5]]


reshape()

In [7]:
a = np.random.randint(1,10,(2,3))
arr_print(a)
b = a.reshape(3,2,1)
arr_print(b)
b[0][0][0] = 999
arr_print(b)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[6 1 6]
 [6 3 1]]
type: <class 'numpy.ndarray'>
shape: (3, 2, 1), dimension : 3, dtype : int32
numpy 배열의 데이터
 [[[6]
  [1]]

 [[6]
  [6]]

 [[3]
  [1]]]
type: <class 'numpy.ndarray'>
shape: (3, 2, 1), dimension : 3, dtype : int32
numpy 배열의 데이터
 [[[999]
  [  1]]

 [[  6]
  [  6]]

 [[  3]
  [  1]]]
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[999   1   6]
 [  6   3   1]]


resize()

In [8]:
a = np.random.randint(1,10,(2,6))
arr_print(a)
b = np.resize(a, (6,2))
arr_print(b)
a.resize((6,2))
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (2, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 7 8 3 3 4]
 [8 7 8 1 4 3]]
type: <class 'numpy.ndarray'>
shape: (6, 2), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 7]
 [8 3]
 [3 4]
 [8 7]
 [8 1]
 [4 3]]
type: <class 'numpy.ndarray'>
shape: (6, 2), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 7]
 [8 3]
 [3 4]
 [8 7]
 [8 1]
 [4 3]]


In [9]:
a.reshape(2,10)
arr_print(a)

ValueError: cannot reshape array of size 12 into shape (2,10)

In [10]:
a.resize(2,10)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (2, 10), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 7 8 3 3 4 8 7 8 1]
 [4 3 0 0 0 0 0 0 0 0]]


In [11]:
a.resize(2,4)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (2, 4), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 7 8 3]
 [3 4 8 7]]


### 3. 배열 요소 추가

append()

In [13]:
a = np.random.randint(1,10,(3,3))
arr_print(a)
b = np.random.randint(10,19,(3,3))
arr_print(b)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 6 9]
 [4 7 8]
 [5 9 2]]
type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[18 11 13]
 [13 10 14]
 [11 14 11]]


In [15]:
# axis를 지정하지 않은 경우
result = np.append(a,b)
arr_print(result)

type: <class 'numpy.ndarray'>
shape: (18,), dimension : 1, dtype : int32
numpy 배열의 데이터
 [ 9  6  9  4  7  8  5  9  2 18 11 13 13 10 14 11 14 11]


In [17]:
# axis = 0으로 지정한 경우
result = np.append(a,b, axis=0)
arr_print(result)

print('a의 shape : {}, a의 shape[0]: {}, a의 shape[1]: {}'.format(a.shape, a.shape[0], a.shape[1]))

type: <class 'numpy.ndarray'>
shape: (6, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 9  6  9]
 [ 4  7  8]
 [ 5  9  2]
 [18 11 13]
 [13 10 14]
 [11 14 11]]
a의 shape : (3, 3), a의 shape[0]: 3, a의 shape[1]: 3


In [18]:
# axis = 1으로 지정한 경우
result = np.append(a,b, axis=1)
arr_print(result)

type: <class 'numpy.ndarray'>
shape: (3, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 9  6  9 18 11 13]
 [ 4  7  8 13 10 14]
 [ 5  9  2 11 14 11]]


insert()

In [19]:
a = np.random.randint(1, 10, (3,3))
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[3 2 1]
 [4 1 4]
 [5 6 7]]


In [21]:
arr_print(np.insert(a,1, 9999))
arr_print(np.insert(a,1, 9999, axis=0))
arr_print(np.insert(a,1, 9999, axis=1))

type: <class 'numpy.ndarray'>
shape: (10,), dimension : 1, dtype : int32
numpy 배열의 데이터
 [   3 9999    2    1    4    1    4    5    6    7]
type: <class 'numpy.ndarray'>
shape: (4, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[   3    2    1]
 [9999 9999 9999]
 [   4    1    4]
 [   5    6    7]]
type: <class 'numpy.ndarray'>
shape: (3, 4), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[   3 9999    2    1]
 [   4 9999    1    4]
 [   5 9999    6    7]]


### 4. 배열 요소 삭제

delete()

In [22]:
a = np.random.randint(1, 10, (3,3))
arr_print(a)

arr_print(np.delete(a,1))
arr_print(np.delete(a,1, axis=0))
arr_print(np.delete(a,1, axis=1))

type: <class 'numpy.ndarray'>
shape: (3, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 2 6]
 [3 5 4]
 [6 7 6]]
type: <class 'numpy.ndarray'>
shape: (8,), dimension : 1, dtype : int32
numpy 배열의 데이터
 [9 6 3 5 4 6 7 6]
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 2 6]
 [6 7 6]]
type: <class 'numpy.ndarray'>
shape: (3, 2), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 6]
 [3 4]
 [6 6]]


### 5. 배열 결합

concatenate()

In [26]:
a = np.random.randint(1, 10, (2,3))
arr_print(a)
b = np.random.randint(1, 10, (2,3))
arr_print(b)

result = np.concatenate((a,b))
arr_print(result)
result = np.concatenate((a,b), axis=0)
arr_print(result)
result = np.concatenate((a,b), axis=1)
arr_print(result)

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[8 4 5]
 [6 8 1]]
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[5 7 8]
 [7 9 8]]
type: <class 'numpy.ndarray'>
shape: (4, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[8 4 5]
 [6 8 1]
 [5 7 8]
 [7 9 8]]
type: <class 'numpy.ndarray'>
shape: (4, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[8 4 5]
 [6 8 1]
 [5 7 8]
 [7 9 8]]
type: <class 'numpy.ndarray'>
shape: (2, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[8 4 5 5 7 8]
 [6 8 1 7 9 8]]


vstack()

In [27]:
a = np.random.randint(1,10, (2,3))
arr_print(a)
b = np.random.randint(1,10, (2,3))
arr_print(b)

arr_print(np.vstack((a,b)))
arr_print(np.vstack((a,b,a,b)))

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 4 7]
 [6 4 1]]
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[3 2 4]
 [5 5 4]]
type: <class 'numpy.ndarray'>
shape: (4, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 4 7]
 [6 4 1]
 [3 2 4]
 [5 5 4]]
type: <class 'numpy.ndarray'>
shape: (8, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[9 4 7]
 [6 4 1]
 [3 2 4]
 [5 5 4]
 [9 4 7]
 [6 4 1]
 [3 2 4]
 [5 5 4]]


hstack()

In [28]:
a = np.random.randint(1,10, (2,3))
arr_print(a)
b = np.random.randint(1,10, (2,3))
arr_print(b)

arr_print(np.hstack((a,b)))
arr_print(np.hstack((a,b,a,b)))

type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[8 7 6]
 [8 1 9]]
type: <class 'numpy.ndarray'>
shape: (2, 3), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[4 2 4]
 [3 3 6]]
type: <class 'numpy.ndarray'>
shape: (2, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[8 7 6 4 2 4]
 [8 1 9 3 3 6]]
type: <class 'numpy.ndarray'>
shape: (2, 12), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[8 7 6 4 2 4 8 7 6 4 2 4]
 [8 1 9 3 3 6 8 1 9 3 3 6]]


### 6. 배열분리

hsplite()

In [33]:
a = np.arange(1, 25).reshape(4,6)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [38]:
result = np.hsplit(a,3)
print(result)
print(type(result))
print(np.array(result).shape)

[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]
<class 'list'>
(3, 4, 2)


In [40]:
result = np.hsplit(a,[1,3,5])
print(result)
print(type(result))

[array([[ 1],
       [ 7],
       [13],
       [19]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15],
       [20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]]), array([[ 6],
       [12],
       [18],
       [24]])]
<class 'list'>


vsplite()

In [42]:
a = np.arange(1, 25).reshape(4,6)
arr_print(a)

type: <class 'numpy.ndarray'>
shape: (4, 6), dimension : 2, dtype : int32
numpy 배열의 데이터
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [44]:
result = np.vsplit(a,2)
print(result)
print(type(result))
print(np.array(result).shape)

[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]
<class 'list'>
(2, 2, 6)


In [45]:
result = np.vsplit(a,4)
print(result)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]


In [46]:
result = np.vsplit(a,[1,3])
print(result)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]]), array([[19, 20, 21, 22, 23, 24]])]
