In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
def arr_print(arr):
    print('type: {}'.format(type(arr)))
    print('shape: {}, dimension : {}, dtype : {}'.format(arr.shape, arr.ndim, arr.dtype))
    print('numpy 배열의 데이터\n', arr)

In [3]:
arr = np.random.random((2,3,6))
arr_print(arr)

type: <class 'numpy.ndarray'>
shape: (2, 3, 6), dimension : 3, dtype : float64
numpy 배열의 데이터
 [[[0.82408885 0.00201944 0.15593058 0.24140012 0.9172671  0.42745351]
  [0.46793922 0.25477915 0.77102061 0.90525019 0.27929307 0.30086193]
  [0.02061661 0.57895022 0.161546   0.4066954  0.94172076 0.82596261]]

 [[0.15536485 0.46535913 0.07808959 0.88002767 0.24065267 0.58371494]
  [0.5580266  0.52143883 0.36356923 0.50812262 0.64957727 0.04815799]
  [0.79075203 0.42898162 0.09929139 0.79543486 0.56284532 0.04695778]]]


In [12]:
print('배열의 타입 : {}'.format(type(arr)))
print('배열의 shape : {}'.format(arr.shape))
print('배열의 길이(면) : {}'.format(len(arr)))
print('배열의 길이(행) : {}'.format(len(arr[0])))
print('배열의 길이(열) : {}'.format(len(arr[0][0])))
print('배열의 차원 : {}'.format(arr.ndim))
print('배열의 요소 수 : {}'.format(arr.size))
print('배열의 데이터 타입 : {}'.format(arr.dtype))
print('배열의 데이터 타입 이름 : {}'.format(arr.dtype.name))

배열의 타입 : <class 'numpy.ndarray'>
배열의 shape : (2, 3, 6)
배열의 길이(면) : 2
배열의 길이(행) : 3
배열의 길이(열) : 6
배열의 차원 : 3
배열의 요소 수 : 36
배열의 데이터 타입 : float64
배열의 데이터 타입 이름 : float64


In [14]:
print(arr.astype(np.int))
print(arr)

[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]]
[[[0.82408885 0.00201944 0.15593058 0.24140012 0.9172671  0.42745351]
  [0.46793922 0.25477915 0.77102061 0.90525019 0.27929307 0.30086193]
  [0.02061661 0.57895022 0.161546   0.4066954  0.94172076 0.82596261]]

 [[0.15536485 0.46535913 0.07808959 0.88002767 0.24065267 0.58371494]
  [0.5580266  0.52143883 0.36356923 0.50812262 0.64957727 0.04815799]
  [0.79075203 0.42898162 0.09929139 0.79543486 0.56284532 0.04695778]]]
